name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
          enforce-lockfile: true

      - name: Build web
        working-directory: example
        run: flutter build web --base-href "/flutter_webrtc_zxing/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
